title: Phillip E Wilson Jr.
logo: /assets/img/Profile Pic2.jpg
description: Recent Graduate Student at Old Dominion University
show_download: True 
theme: jekyll-theme-minimal
#logo:
#description: text below image
#show_download: False 
#theme :jekyll-theme-mininmal
