title: Phillip E Wilson Jr.
logo: /assets/img/profile2.jpg
description: Current Graduate Student pursuing a Masters Degree in Computer Science
show_download: True 
theme: jekyll-theme-minimal
#logo:
#description: text below image
#show_download: False 
#theme :jekyll-theme-mininmal
